public class Constant {
    
    public static final String OTI_TYPE 		= 'OTI';
    public static final String SAAS_TYPE 		= 'SAAS';
    public static final String SAAS_OTI_TYPE 	= 'OTI + SAAS';
    public static final String PROFILE_INSIDE_SALES_TEAM 	= 'Inside Sales';
    public static final String PROFILE_AM_TEAM 	= 'AM';
    public static final String PROFILE_ENTERPRISE_TEAM 	= 'Enterprise';
}